[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_basics = "HpKJxxMy5NAiSbJ1q6qBCYBtftJ4ZG76ZbC9DFmZMk2X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
